{% set name = "compas_pb" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compas_pb-{{ version }}.tar.gz
  sha256: d63b791fc709499e19f0c8d2754d7d35ad0e893fa373ca6aa220969eb55470f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66.0
    - pip
  run:
    - python >={{ python_min }}
    - compas >=2,<3
    - protobuf >=6.31.1

test:
  imports:
    - compas_pb
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gramaziokohler/compas_pb
  summary: Protobuf extension for COMPAS Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chenkasirer
